def let(x):
	if x[0] == "A":
		print(" ")
		print("AAAAA")
		print("A   A")
		print("AAAAA")
		print("A   A")
		print("A   A")
		print(" ")
	if x[0] == "B":
		print(" ")
		print("BBBB")
		print("B   B")
		print("BBBBB")
		print("B   B")
		print("BBBB")
		print(" ")
	if x[0] == "C":
		print(" ")
		print("CCCCC")
		print("C")
		print("C")
		print("C")
		print("CCCCC")
		print(" ")
	if x[0] == "D":
		print(" ")
		print("DDDD")
		print("D   D")
		print("D   D")
		print("D   D")
		print("DDDD")
		print(" ")
	if x[0] == "E":
		print(" ")
		print("EEEEE")
		print("E")
		print("EEEEE")
		print("E")
		print("EEEEE")
		print(" ")
	if x[0] == "F":
		print(" ")
		print("FFFFF")
		print("F")
		print("FFFF")
		print("F")
		print("F")
		print(" ")
	if x[0] == "G":
		print(" ")
		print("GGGGG")
		print("G")
		print("G  GG")
		print("G   G")
		print("GGGGG")
		print(" ")
	if x[0] == "H":
		print(" ")
		print("H   H")
		print("H   H")
		print("HHHHH")
		print("H   H")
		print("H   H")
		print(" ")
	if x[0] == "I":
		print(" ")
		print("IIIII")
		print("  I")
		print("  I")
		print("  I")
		print("IIIII")
		print(" ")
	if x[0] == "J":
		print(" ")
		print("JJJJJ")
		print("  J")
		print("  J")
		print("  J")
		print("JJJ")
		print(" ")
	if x[0] == "K":
		print(" ")
		print("K   K")
		print("K  K")
		print("KKK")
		print("K  K")
		print("K   K")
		print(" ")
	if x[0] == "L":
		print(" ")
		print("L")
		print("L")
		print("L")
		print("L")
		print("LLLLL")
		print(" ")
	if x[0] == "M":
		print(" ")
		print("M   M")
		print("MM MM")
		print("M M M")
		print("M   M")
		print("M   M")
		print(" ")
	if x[0] == "N":
		print(" ")
		print("N   N")
		print("NN  N")
		print("N N N")
		print("N  NN")
		print("N   N")
		print(" ")
	if x[0] == "O":
		print(" ")
		print("OOOOO")
		print("O   O")
		print("O   O")
		print("O   O")
		print("OOOOO")
		print(" ")
	if x[0] == "P":
		print(" ")
		print("PPPPP")
		print("P   P")
		print("PPPPP")
		print("P")
		print("P")
		print(" ")
	if x[0] == "Q":
		print(" ")
		print(" QQQ ")
		print("Q   Q")
		print("Q Q Q")
		print(" QQQ")
		print("    Q")
		print(" ")
	if x[0] == "R":
		print(" ")
		print("RRRRR")
		print("R   R")
		print("RRRRR")
		print("R  R  ")
		print("R   R")
		print(" ")
	if x[0] == "S":
		print(" ")
		print("SSSSS")
		print("S")
		print("SSSSS")
		print("    S")
		print("SSSSS")
		print (" ")
	if x[0] == "T":
		print(" ")
		print("TTTTT")
		print("  T")
		print("  T")
		print("  T")
		print("  T")
		print (" ")
	if x[0] == "U":
		print(" ")
		print("U   U")
		print("U   U")
		print("U   U")
		print("U   U")
		print("UUUUU")
		print (" ")
	if x[0] == "V":
		print(" ")
		print("V   V")
		print("V   V")
		print("V   V")
		print(" V V")
		print("  V")
		print (" ")
	if x[0] == "W":
		print(" ")
		print("W   W")
		print("W   W")
		print("WW WW")
		print("W W W")
		print("W W W")
		print (" ")
	if x[0] == "X":
		print(" ")
		print("X   X")
		print(" X X")
		print("  X")
		print(" X X")
		print("X   X")
		print (" ")
	if x[0] == "Y":
		print(" ")
		print("Y   Y")
		print(" Y Y")
		print("  Y")
		print("  Y")
		print("  Y")
		print(" ")
	if x[0] == "Z":
		print(" ")
		print("ZZZZZ")
		print("   Z")
		print("  Z")
		print(" Z   ")
		print("ZZZZZ")
		print (" ")
	if x[0] == "a":
		print(" ")
		print("AAAAA")
		print("A   A")
		print("AAAAA")
		print("A   A")
		print("A   A")
		print(" ")
	if x[0] == "b":
		print(" ")
		print("BBBB")
		print("B   B")
		print("BBBBB")
		print("B   B")
		print("BBBB")
		print(" ")
	if x[0] == "c":
		print(" ")
		print("CCCCC")
		print("C")
		print("C")
		print("C")
		print("CCCCC")
		print(" ")
	if x[0] == "d":
		print(" ")
		print("DDDD")
		print("D   D")
		print("D   D")
		print("D   D")
		print("DDDD")
		print(" ")
	if x[0] == "e":
		print(" ")
		print("EEEEE")
		print("E")
		print("EEEEE")
		print("E")
		print("EEEEE")
		print(" ")
	if x[0] == "f":
		print(" ")
		print("FFFFF")
		print("F")
		print("FFFF")
		print("F")
		print("F")
		print(" ")
	if x[0] == "g":
		print(" ")
		print("GGGGG")
		print("G")
		print("G  GG")
		print("G   G")
		print("GGGGG")
		print(" ")
	if x[0] == "h":
		print(" ")
		print("H   H")
		print("H   H")
		print("HHHHH")
		print("H   H")
		print("H   H")
		print(" ")
	if x[0] == "i":
		print(" ")
		print("IIIII")
		print("  I")
		print("  I")
		print("  I")
		print("IIIII")
		print(" ")
	if x[0] == "j":
		print(" ")
		print("JJJJJ")
		print("  J")
		print("  J")
		print("  J")
		print("JJJ")
		print(" ")
	if x[0] == "k":
		print(" ")
		print("K   K")
		print("K  K")
		print("KKK")
		print("K  K")
		print("K   K")
		print(" ")
	if x[0] == "l":
		print(" ")
		print("L")
		print("L")
		print("L")
		print("L")
		print("LLLLL")
		print(" ")
	if x[0] == "m":
		print(" ")
		print("M   M")
		print("MM MM")
		print("M M M")
		print("M   M")
		print("M   M")
		print(" ")
	if x[0] == "n":
		print(" ")
		print("N   N")
		print("NN  N")
		print("N N N")
		print("N  NN")
		print("N   N")
		print(" ")
	if x[0] == "o":
		print(" ")
		print("OOOOO")
		print("O   O")
		print("O   O")
		print("O   O")
		print("OOOOO")
		print(" ")
	if x[0] == "p":
		print(" ")
		print("PPPPP")
		print("P   P")
		print("PPPPP")
		print("P")
		print("P")
		print(" ")
	if x[0] == "q":
		print(" ")
		print(" QQQ ")
		print("Q   Q")
		print("Q Q Q")
		print(" QQQ")
		print("    Q")
		print(" ")
	if x[0] == "r":
		print(" ")
		print("RRRRR")
		print("R   R")
		print("RRRRR")
		print("R  R  ")
		print("R   R")
		print(" ")
	if x[0] == "s":
		print(" ")
		print("SSSSS")
		print("S")
		print("SSSSS")
		print("    S")
		print("SSSSS")
		print (" ")
	if x[0] == "t":
		print(" ")
		print("TTTTT")
		print("  T")
		print("  T")
		print("  T")
		print("  T")
		print (" ")
	if x[0] == "u":
		print(" ")
		print("U   U")
		print("U   U")
		print("U   U")
		print("U   U")
		print("UUUUU")
		print (" ")
	if x[0] == "v":
		print(" ")
		print("V   V")
		print("V   V")
		print("V   V")
		print(" V V")
		print("  V")
		print (" ")
	if x[0] == "w":
		print(" ")
		print("W   W")
		print("W   W")
		print("WW WW")
		print("W W W")
		print("W W W")
		print (" ")
	if x[0] == "x":
		print(" ")
		print("X   X")
		print(" X X")
		print("  X")
		print(" X X")
		print("X   X")
		print (" ")
	if x[0] == "y":
		print(" ")
		print("Y   Y")
		print(" Y Y")
		print("  Y")
		print("  Y")
		print("  Y")
		print(" ")
	if x[0] == "z":
		print(" ")
		print("ZZZZZ")
		print("   Z")
		print("  Z")
		print(" Z   ")
		print("ZZZZZ")
		print (" ")
